// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYxPdtfQj53x38-scADg3LP6Sk4xRqVw',
    appId: '1:953051059287:android:f7a17bc3dd083ce5753f12',
    messagingSenderId: '953051059287',
    projectId: 'notes-app-c1f14',
    storageBucket: 'notes-app-c1f14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhECSfOKLJJ0g5MJg4L_pFT6eSsJb4gtM',
    appId: '1:953051059287:ios:cd5721052e8ebe58753f12',
    messagingSenderId: '953051059287',
    projectId: 'notes-app-c1f14',
    storageBucket: 'notes-app-c1f14.appspot.com',
    androidClientId: '953051059287-9k111lk9eedpa4k60np369s8u80qqqe8.apps.googleusercontent.com',
    iosClientId: '953051059287-enf4vto6kmu6hb9vn3ssa4jcttmdbv42.apps.googleusercontent.com',
    iosBundleId: 'com.wanseaba.firebaseNotes',
  );
}
